layla/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from layla import settings

admin.site.site_header = 'Layla Admin Paneli'

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('pages.urls')),
                  path('account/', include('account.urls')),
                  path('satis/', include('satis.urls')),
                  path('payment/', include('payment.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/models.py
from django.db import models
from django.urls import reverse
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

class Kategori(MPTTModel):
    baslik = models.CharField(max_length=30)
    sira = models.IntegerField()
    aktif = models.BooleanField(default=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    class MPTTMeta:
        order_insertion_by = ['baslik']

    class Meta:
        app_label = 'pages'
    def __str__(self):
        full_path = [self.baslik]
        k = self.parent
        while k is not None:
            full_path.append(k.baslik)
            k = k.parent
        return '/'.join(full_path[::-1])

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'aktif': self.aktif})

class Urun(models.Model):
    kategori = models.ForeignKey(Kategori, on_delete=models.CASCADE)
    aciklama = models.CharField(max_length=255)
    isim = models.CharField(max_length=255, verbose_name='İSİM')
    kod = models.CharField(max_length=4, blank=True, null=True)
    aciklama = models.CharField(max_length=255, blank=True)
    kod = models.CharField(max_length=24, blank=True)
    fiyat = models.DecimalField(max_digits=10, decimal_places=2)
    stok_durumu = models.IntegerField(default=0)
    count = models.IntegerField(default=0)
    resim = models.ImageField(upload_to="products/%Y/%m/%d/", default="products/default_product_image.jpg")

    aktif = models.BooleanField(default=True)
    class Meta:
        ordering = ['-aktif', 'isim']
        verbose_name = u'Urun'
        verbose_name_plural = u'Urunler(Urunlar)'

    def __str__(self):
        return self.isim

class ContactForm(models.Model):
    YENI = 'Y'
    OKUNDU = 'O'
    KAPANDI = 'K'
    DURUM_SECENEKLERI = (
        (YENI, 'Yeni'),
        (OKUNDU, 'Okundu'),
        (KAPANDI, 'Kapandı'),
    )
    isim = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    telefon = models.CharField(blank=True, max_length=20)
    baslik = models.CharField(blank=True, max_length=50)
    mesaj = models.CharField(blank=True, max_length=255)
    ip = models.CharField(blank=True, max_length=20)
    admin_notu = models.CharField(blank=True, max_length=100)
    durum = models.CharField(max_length=10, choices=DURUM_SECENEKLERI, default=YENI)
    olusturma_tarihi = models.DateTimeField(auto_now_add=True, blank=True)
    guncelleme_tarihi = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.isim
    class Meta:
        verbose_name = 'İletişim Formu'
        verbose_name_plural = 'İletişim Formları'

templates/partials/_account_modal.html
{% load static %}
<div class="modal" id="myModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="wrapper">
                <div class="d-flex flex-row-reverse">
                    <a type="button" class="pop-up-close-btn" data-bs-dismiss="modal"><i
                            class="fa-sharp fa-solid fa-xmark close-color"></i></a>
                </div>
                <div class="title-text">
                    <div class="title login">Giriş Yap</div>
                    <div class="title signup">Kayıt Ol</div>
                </div>
                <div class="form-container">
                    <div class="slide-controls">
                        <input class="account-radio" type="radio" name="slider" id="login" checked>
                        <input class="account-radio" type="radio" name="slider" id="signup">
                        <label for="login" class="slide login">Giriş Yap</label>
                        <label for="signup" class="slide signup">Kayıt Ol</label>
                        <div class="slide-tab"></div>
                    </div>
                    <div class="form-inner">
                        <p class="text-white text-center bg-danger mt-2 uyari" id="hata-bastirs"></p>
                        {% include 'partials/_loginform.html' %}

                        {% include 'partials/_signup.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/partials/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Layla - Butik</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Layla - Butik" name="keywords">
    <meta content="Layla - Butik" name="description">

    <!-- Favicon -->
    <link href="{% static 'theme/img/layla.jpeg' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- Alertify CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
    <!-- Alertify Default theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'theme/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'theme/css/style.css' %}" rel="stylesheet">
    <style>
        .list-group-item.active {
            background-color: transparent !important;
            border-color: transparent !important;
            color: #D19C97; /* Aktif olan metnin rengi */
        }
        
        .list-group-item.active .fas {
            color: #D19C97; /* Aktif olan ikonun rengi */
        }
        
        .list-group-item {
            border: none !important;
        }

        .list-group-item:hover {
            background-color: transparent !important;
            border-color: transparent !important;
        }
        
        .list-group-item:hover .fas {
            color: #D19C97; /* Mouse üzerindeyken ikon rengi */
        }
        
        .list-group-item:hover {
            color: #D19C97; /* Mouse üzerindeyken metin rengi */
        }
        
    </style>
</head>
<body>

{% include 'partials/_navbar.html' %}

{% include 'partials/_account_modal.html' %}

{% block content %}
{% endblock %}

{% include 'partials/_footer.html' %}
<script src="{% static 'js/boostrap.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/scroll.js' %}"></script>
{#    <script src="{% static 'js/shrinknavbar.js' %}"></script>#}
<script src="{% static 'js/kayit-ol.js' %}"></script>
<script src="{% static 'js/navbar-style.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.1.js"></script>
</body>

</html>

templates/partials/_footer.html
{% load static %}
<!-- Footer Start -->
<div class="container-fluid bg-secondary text-dark mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <a href="" class="text-decoration-none">
                <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">L</span>ayla Butik</h1>
            </a>
            <p>Butik sitemizde size özel ürünleri keşfedin. En yeni koleksiyonlarımız ve avantajlı fiyatlarımızla sizi bekliyoruz!</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Batı mah, Pendik, İstanbul</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@layla.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Hızlı Linkler</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="{% url 'index.html' %}"><i class="fa fa-angle-right mr-2"></i>Anasayfa</a>
                        <a class="text-dark mb-2" href="{% url 'products' %}"><i class="fa fa-angle-right mr-2"></i>Ürünler</a>
                        <a class="text-dark mb-2" href="{% url 'contact' %}"><i class="fa fa-angle-right mr-2"></i>Bize Ulaş</a>
                        {% if request.user.is_authenticated %}
                        <a class="text-dark mb-2" href="{% url 'anasayfa' %}"><i class="fa fa-angle-right mr-2"></i>Hesabım</a>
                        <a class="text-dark mb-2" href="{% url 'logout' %}"><i class="fa fa-angle-right mr-2"></i>Çıkış Yap</a>
                        {% else %}
                        <a class="text-dark mb-2" data-bs-toggle="modal" data-bs-target="#myModal"><i class="fa fa-angle-right mr-2"></i>Layla'ya Giriş</a>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Kategoriler</h5>
                    <div class="d-flex flex-column justify-content-start">
                        {% for kategori in ana_kategoriler %}
                            {% if forloop.counter <= 10 %}
                            <a class="text-dark mb-2" href="{% url 'urunler_by_kategori' kategori.id %}"><i class="fa fa-angle-right mr-2"></i>{{ kategori.baslik }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <img class="img-fluid rounded-circle" src="{% static 'theme/img/layla.jpeg' %}" alt="layla"
                    style="max-width: 200px; max-height: 200px;"/></h1>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top border-light mx-xl-5 py-4">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-dark">
                &copy; <a class="text-dark font-weight-semi-bold" href="https://www.laylabutik.com/">laylabutik.com</a>. Tüm hakları saklıdır.
                <a href="" target="_blank"> Sinan Aslan</a> tarafından yapılmıştır.
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="{% static 'theme/img/payments.png' %}" alt="">
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

{% if request.user.is_authenticated %}
    <script>
        function basketItemQuantity() {
            $.ajax({
                url: '/satis/sepet_urun_adeti/',
                type: 'GET',
                success: function(data) {
                    if (data) {
                        if(data.sepet_urun_adeti>0){
                            updateSepetUrunAdeti(data.sepet_urun_adeti);
                        }
                    } else {
                        console.log('Hata:', data.error);
                    }
                },
                error: function(error) {
                    console.log(error);
                }
            });
        }
        function updateSepetUrunAdeti(sepetUrunAdeti) {
            var sepetUrunAdetiBadge = document.getElementById('sepetUrunAdetiBadge');
            if (sepetUrunAdetiBadge) {
                sepetUrunAdetiBadge.textContent = sepetUrunAdeti;
            }
        }
    
        // Sayfa yüklendiğinde ve diğer olaylarda sepetteki ürün adetini al
        document.addEventListener('DOMContentLoaded', function () {
            basketItemQuantity();
        });
    </script>
{% endif %}
<script src="https://cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
<script>
    {% if messages %}
        {% for flashmsg in messages %}
            {% if flashmsg.tags == 'success'%}
                alertify.set('notifier','position', 'top-right');
                alertify.success('{{flashmsg}}');
            {% elif flashmsg.tags == 'error' %}
                alertify.set('notifier','position', 'top-right');
                alertify.error('{{flashmsg}}');
            {% endif %}
        {% endfor %}
    {% endif %}
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'theme/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'theme/lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Contact Javascript File -->
<script src="{% static 'theme/mail/jqBootstrapValidation.min.js' %}"></script>
<script src="{% static 'theme/mail/contact.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'theme/js/main.js' %}"></script>

templates/partials/_loginform.html
{% load static %}

<form method="POST" action="{% url 'login' %}" class="login" id="login-form">
    {% csrf_token %}
    
    <p class="text-white text-center bg-danger mt-2 uyari" id="hata-bastir-login"></p>

    <div class="field">
        <input type="email" name="email" id="email" class="form-control"  placeholder="E-Post Adresiniz" required>
    </div>
    <div class="field">
        <input type="password" name="password" id="password" class="form-control" placeholder="Şifreniz" required>
    </div>
    <div class="pass-link"><a href="{% url 'forget-password' %}">Şifrenizi mi unuttunuz?</a></div>
    <div class="field">
        <button type="submit" id="login-link">Giriş Yap</button>
    </div>
    <div class="signup-link">Üye değil misiniz? <a href="#">Şimdi Kayıt Ol</a></div>
</form>

<script src="https://code.jquery.com/jquery-3.6.1.js"></script>
<script>

    $("#login-link").click(function (e) {

        var formData = document.getElementById("login-form"); //.serialize()
        var datas = {};
        for (let i = 0; i < formData.length; i++) {
            const element = formData[i];
            datas[element.name] = element.value;
        }
        console.log(datas)
        var postDATA = JSON.stringify({
            'data': datas
        });

        $('#spinner-div-login').show();
        $.ajax({
            url: window.location.origin + '/account/login',
            type: "POST",
            dataType: "json",
            data: postDATA,
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                "X-CSRFToken": getCookie("csrftoken"), // don't forget to include the 'getCookie' function
            },
            success: (data) => {
                var url = window.location.origin + '/'
                window.location.href = url;
            },
            complete: function () {
                $('#spinner-div-login').hide();
            },
            error: (error) => {
                login_hata_bastir(error);
            }
        });

        e.preventDefault();
    })


    function login_hata_bastir(errors) {
            if (errors["responseJSON"]["error"]["__all__"]) {
                $("#hata-bastir-login").text(errors["responseJSON"]["error"]["__all__"])
            }
            else{
                $("#hata-bastir-login").text(errors["responseJSON"]["error"])
            }
        }

</script>

templates/partials/_navbar.html
{% load static %}
<!-- Topbar Start -->
<div class="container-fluid">
    <div class="row bg-secondary py-2 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center">
                <a class="text-dark" href="">SSS</a>
                <span class="text-muted px-2">|</span>
                <a class="text-dark" href="">Yardım</a>
                <span class="text-muted px-2">|</span>
                <a class="text-dark" href="">Destek</a>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <a class="text-dark px-2" href="">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a class="text-dark px-2" href="">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="text-dark px-2" href="">
                    <i class="fab fa-linkedin-in"></i>
                </a>
                <a class="text-dark px-2" href="">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="text-dark pl-2" href="">
                    <i class="fab fa-youtube"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="row align-items-center py-3 px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a href="{% url 'index.html' %}" class="text-decoration-none">
                <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">L</span>ayla Butik</h1>
            </a>
        </div>
        <div class="col-lg-6 col-6 text-left">
            <form method="get" id="site-searchform" action="{% url 'search' %}">
                <div class="input-group">
                    <input type="text" class="form-control" name="search" placeholder="Ürün ara">
                    <div class="input-group-append">
                        <span class="input-group-text bg-transparent text-primary">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-3 col-6 text-right">
            <a href="" class="btn border">
                <i class="fas fa-heart text-primary"></i>
                <span class="badge">0</span>
            </a>
            <a href="{% url 'sepetim' %}" class="btn border">
                <i class="fas fa-shopping-cart text-primary"></i>
                <span id="sepetUrunAdetiBadge" class="badge">0</span>
            </a>
        </div>
    </div>
</div>
<!-- Topbar End -->


<!-- Navbar Start -->
<div class="container-fluid">
    <div class="row border-top px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                <h6 class="m-0">Kategoriler</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            {% if '/' == request.path %}
            <nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0" id="navbar-vertical">
            {% else %}
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 1;">
            {% endif %}
                <div class="navbar-nav w-100 overflow-hidden">
                    {% for kategori in ana_kategoriler %}
                        {% if forloop.counter <= 10 %}
                            <a href="{% url 'urunler_by_kategori' kategori.id %}" class="nav-item nav-link">{{ kategori.baslik }}</a>
                        {% endif %}
                    {% endfor %}
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">L</span>ayla Butik</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{% url 'index.html' %}" class="nav-item nav-link {% if request.path == '/' %}active{% endif %}">Anasayfa</a>
                        <a href="{% url 'products' %}" class="nav-item nav-link {% if '/urunler/' in request.path %}active{% endif %}">Ürünler</a>
                        {% if request.user.is_authenticated %}
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle {% if '/sepetim/' in request.path %}active{% endif %}" data-toggle="dropdown">Bana Özel</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                <a href="{% url 'sepetim' %}" class="dropdown-item">Sepetim</a>
                                <a href="" class="dropdown-item">Favorilerim</a>
                            </div>
                        </div>
                        {% endif %}
                        <a href="{% url 'contact' %}" class="nav-item nav-link {% if request.path == '/iletisim/' %}active{% endif %}">Bize Ulaş</a>
                    </div>
                    {% if request.user.is_authenticated %}
                    <div class="navbar-nav ml-auto py-0">
                        <a href="{% url 'anasayfa' %}" class="nav-item nav-link {% if '/account/' in request.path %}active{% endif %}">Hesabım</a>
                        <a href="{% url 'logout' %}" class="nav-item nav-link">Çıkış Yap</a>
                    </div>
                    {% else %}
                    <div class="navbar-nav ml-auto py-0">
                        <a class="nav-item nav-link" data-bs-toggle="modal" data-bs-target="#myModal">Layla'ya Giriş</a>
                    </div>
                    {% endif %}
                </div>
            </nav>
            {% if '/' == request.path %}
            <div id="header-carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active" style="height: 410px;">
                        <img class="img-fluid" src="{% static 'theme/img/carousel-1.jpg' %}" alt="Image">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h4 class="text-light text-uppercase font-weight-medium mb-3">İlk Siparişinizde %10 İndirim</h4>
                                <h3 class="display-4 text-white font-weight-semi-bold mb-4">Moda Elbise</h3>
                                <a href="{% url 'products' %}" class="btn btn-light py-2 px-3">Satın Al</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item" style="height: 410px;">
                        <img class="img-fluid" src="{% static 'theme/img/carousel-2.jpg' %}" alt="Image">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h4 class="text-light text-uppercase font-weight-medium mb-3">İlk Siparişinizde %10 İndirim</h4>
                                <h3 class="display-4 text-white font-weight-semi-bold mb-4">Makul fiyat</h3>
                                <a href="{% url 'products' %}" class="btn btn-light py-2 px-3">Satın Al</a>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
                    <div class="btn btn-dark" style="width: 45px; height: 45px;">
                        <span class="carousel-control-prev-icon mb-n2"></span>
                    </div>
                </a>
                <a class="carousel-control-next" href="#header-carousel" data-slide="next">
                    <div class="btn btn-dark" style="width: 45px; height: 45px;">
                        <span class="carousel-control-next-icon mb-n2"></span>
                    </div>
                </a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<!-- Navbar End -->

templates/partials/_signup.html
{% load static %}

<form method="POST" action="/account/register" class="signup" id="sign-up-form">
    {% csrf_token %}
    <p class="text-white text-center bg-danger mt-2 uyari" id="hata-bastir"></p>
    
    <div class="field">
        <input type="email" name="email" class="form-control" placeholder="E-mail" required id="id_email">
    </div>
    <div class="field">
        <input type="text" name="isim" class="form-control" placeholder="İsim" required id="id_isim">
    </div>
    
     <div class="field">
        <input type="text" name="soyisim" class="form-control" placeholder="Soyisim" required id="id_isim">
    </div>

    <div class="field">
        <input type="password" name="password" class="form-control" placeholder="Parola" required id="id_password">
    </div>
    <div class="field">
        <button id="kayit-ol-btn" type="submit">Kayıt Ol</button>
    </div>
</form>